# Generated by Django 3.0 on 2021-10-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211002_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('available_offers', models.TextField(max_length=10000)),
                ('service', models.TextField(max_length=10000)),
                ('seller', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=10000)),
                ('specification', models.TextField(max_length=20000)),
                ('highlights', models.TextField(max_length=10000)),
                ('img1', models.ImageField(upload_to='pic')),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('gender', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('available_offers', models.TextField(max_length=10000)),
                ('service', models.TextField(max_length=10000)),
                ('color', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('seller', models.CharField(max_length=500)),
                ('product_details', models.TextField(max_length=20000)),
                ('img1', models.ImageField(upload_to='pic')),
                ('img2', models.ImageField(upload_to='pic')),
                ('img3', models.ImageField(upload_to='pic')),
                ('img4', models.ImageField(upload_to='pic')),
                ('img5', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
