# Generated by Django 3.0 on 2021-10-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211010_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='system_languages',
            field=models.CharField(max_length=1000),
        ),
    ]
