# Generated by Django 3.0 on 2021-10-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211010_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='company_name',
            field=models.CharField(default='NA', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fashion',
            name='price',
            field=models.IntegerField(),
        ),
    ]
